### ISSUE TITLE
Make gem compatible with frozen string literal

### ISSUE THREAD

**Issue by temirov** [miyucy/snappy#23]
way to reproduce: run tests with `RUBYOPT=--enable-frozen-string-literal` option

```
Error: test_optimized_recommendation_submission(TestApp): RuntimeError: can't modify frozen String
/Users/vadymtemirov/.gem/ruby/2.4.1/gems/snappy-0.0.15/lib/snappy/writer.rb:6:in `force_encoding'
/Users/vadymtemirov/.gem/ruby/2.4.1/gems/snappy-0.0.15/lib/snappy/writer.rb:6:in `<class:Writer>'
/Users/vadymtemirov/.gem/ruby/2.4.1/gems/snappy-0.0.15/lib/snappy/writer.rb:2:in `<module:Snappy>'
/Users/vadymtemirov/.gem/ruby/2.4.1/gems/snappy-0.0.15/lib/snappy/writer.rb:1:in `<top (required)>'
/Users/vadymtemirov/.gem/ruby/2.4.1/gems/snappy-0.0.15/lib/snappy.rb:6:in `require'
/Users/vadymtemirov/.gem/ruby/2.4.1/gems/snappy-0.0.15/lib/snappy.rb:6:in `<top (required)>'
```

**Comment by miyucy** [comment]
Thanks for reporting!
