### ISSUE TITLE
Installation of Snappy is failing in Docker container

### ISSUE THREAD

**Issue by AkshayDubey29** [miyucy/snappy#28]
Hi,
While installing the snappy in docker container I am getting below error.
Please do help me to resolve the issue.

22:22:11 ERROR:  Error installing snappy:
22:22:11 	ERROR: Failed to build gem native extension.
22:22:11 
22:22:11     current directory: /usr/lib/ruby/gems/2.4.0/gems/snappy-0.0.15/ext
22:22:11 /usr/bin/ruby -r ./siteconf20180327-646-7algd8.rb extconf.rb
22:22:11 checking for -lsnappy... no
22:22:11 ./autogen.sh: line 3: aclocal: not found
22:22:11 ./autogen.sh: line 3: aclocal: not found
22:22:11 *** extconf.rb failed ***
22:22:11 Could not create Makefile due to some reason, probably lack of necessary
22:22:11 libraries and/or headers.  Check the mkmf.log file for more details.  You may
22:22:11 need configuration options.
22:22:11 
22:22:11 Provided configuration options:
22:22:11 	--with-opt-dir
22:22:11 	--without-opt-dir
22:22:11 	--with-opt-include
22:22:11 	--without-opt-include=${opt-dir}/include
22:22:11 	--with-opt-lib
22:22:11 	--without-opt-lib=${opt-dir}/lib
22:22:11 	--with-make-prog
22:22:11 	--without-make-prog
22:22:11 	--srcdir=.
22:22:11 	--curdir
22:22:11 	--ruby=/usr/bin/$(RUBY_BASE_NAME)
22:22:11 	--with-libsnappy-config
22:22:11 	--without-libsnappy-config
22:22:11 	--with-pkg-config
22:22:11 	--without-pkg-config
22:22:11 	--with-snappylib
22:22:11 	--without-snappylib
22:22:11 extconf.rb:17:in `block in <main>': `autogen.sh` failed (RuntimeError)
22:22:11 	from extconf.rb:14:in `chdir'
22:22:11 	from extconf.rb:14:in `<main>'
22:22:11 
22:22:11 To see why this extension failed to compile, please check the mkmf.log which can be found here:
22:22:11 
22:22:11   /usr/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/snappy-0.0.15/mkmf.log
22:22:11 
22:22:11 extconf failed, exit code 1
22:22:11 
22:22:11 Gem files will remain installed in /usr/lib/ruby/gems/2.4.0/gems/snappy-0.0.15 for inspection.
22:22:11 Results logged to /usr/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/snappy-0.0.15/gem_make.out
22:22:11

**Comment by miyucy** [comment]
Hi
I think your container is lack of some library.

```bash
apt-get install libsnappy-dev
```

```bash
apt-get install libtool automake autoconf
```
