### ISSUE TITLE
Failing to install Snappy on maxOS 12 arm64 with "unknown type name 'constexpr'"

### ISSUE THREAD

**Issue by langalex** [miyucy/snappy#40]
Summary: after installing cmake via homebrew, compilation fails with `./snappy.h:197:10: error: unknown type name 'constexpr'`

Steps to reproduce:

* maxOS version: 12.0 arm64
* ran `brew install autoconf automake libtool`

```
$ brew info autoconf automake libtool
autoconf: stable 2.71 (bottled)
...
Poured from bottle on 2021-10-29 at 22:43:18
...
automake: stable 1.16.5 (bottled)
...
Poured from bottle on 2021-10-29 at 22:43:19
...
libtool: stable 2.4.6 (bottled)
...
Poured from bottle on 2021-10-29 at 22:43:23
```

```
$ ruby --version
ruby 2.6.8p205 (2021-07-07 revision 67951) [arm64-darwin21]
```

first it fails with missing cmake:

```
$ gem install snappy                 
Building native extensions. This could take a while...
ERROR:  Error installing snappy:
	ERROR: Failed to build gem native extension.

    current directory: /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext
/Users/alexanderlang/.asdf/installs/ruby/2.6.8/bin/ruby -I /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/2.6.0 -r ./siteconf20211030-88107-1am0iun.rb extconf.rb
checking for -lsnappy... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/alexanderlang/.asdf/installs/ruby/2.6.8/bin/$(RUBY_BASE_NAME)
	--with-libsnappy-config
	--without-libsnappy-config
	--with-pkg-config
	--without-pkg-config
	--with-snappylib
	--without-snappylib
extconf.rb:12:in ``': No such file or directory - cmake (Errno::ENOENT)
	from extconf.rb:12:in `block (2 levels) in <main>'
	from extconf.rb:11:in `chdir'
	from extconf.rb:11:in `block in <main>'
	from extconf.rb:9:in `chdir'
	from extconf.rb:9:in `<main>'
```

installing cmake. is that the right thing to do?

```
$ brew install cmake
$ brew info cmake
cmake: stable 3.21.4 (bottled), HEAD
```

now failing somewhere in C++:

```
$ gem install snappy
Building native extensions. This could take a while...
ERROR:  Error installing snappy:
	ERROR: Failed to build gem native extension.

    current directory: /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext
/Users/alexanderlang/.asdf/installs/ruby/2.6.8/bin/ruby -I /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/2.6.0 -r ./siteconf20211030-89699-1cndzdg.rb extconf.rb
checking for -lsnappy... no
cp /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/build/config.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/build/snappy-stubs-public.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext
cp /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-c.cc /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-c.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-internal.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-sinksource.cc /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-sinksource.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy.cc /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-stubs-internal.cc /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext/../vendor/snappy/snappy-stubs-internal.h /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext
creating Makefile

current directory: /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext
make "DESTDIR=" clean

current directory: /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0/ext
make "DESTDIR="
compiling api.c
compiling snappy-c.cc
In file included from snappy-c.cc:29:
In file included from ./snappy.h:45:
./snappy-stubs-public.h:54:14: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using int8 = std::int8_t;
             ^
./snappy-stubs-public.h:55:15: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using uint8 = std::uint8_t;
              ^
./snappy-stubs-public.h:56:15: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using int16 = std::int16_t;
              ^
./snappy-stubs-public.h:57:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using uint16 = std::uint16_t;
               ^
./snappy-stubs-public.h:58:15: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using int32 = std::int32_t;
              ^
./snappy-stubs-public.h:59:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using uint32 = std::uint32_t;
               ^
./snappy-stubs-public.h:60:15: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using int64 = std::int64_t;
              ^
./snappy-stubs-public.h:61:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using uint64 = std::uint64_t;
               ^
In file included from snappy-c.cc:29:
./snappy.h:197:10: error: unknown type name 'constexpr'
  static constexpr int kBlockLog = 16;
         ^
./snappy.h:198:10: error: unknown type name 'constexpr'
  static constexpr size_t kBlockSize = 1 << kBlockLog;
         ^
./snappy.h:198:26: error: expected ';' after top level declarator
  static constexpr size_t kBlockSize = 1 << kBlockLog;
                         ^
                         ;
./snappy.h:200:10: error: unknown type name 'constexpr'
  static constexpr int kMinHashTableBits = 8;
         ^
./snappy.h:201:10: error: unknown type name 'constexpr'
  static constexpr size_t kMinHashTableSize = 1 << kMinHashTableBits;
         ^
./snappy.h:201:26: error: expected ';' after top level declarator
  static constexpr size_t kMinHashTableSize = 1 << kMinHashTableBits;
                         ^
                         ;
./snappy.h:203:10: error: unknown type name 'constexpr'
  static constexpr int kMaxHashTableBits = 14;
         ^
./snappy.h:204:10: error: unknown type name 'constexpr'
  static constexpr size_t kMaxHashTableSize = 1 << kMaxHashTableBits;
         ^
./snappy.h:204:26: error: expected ';' after top level declarator
  static constexpr size_t kMaxHashTableSize = 1 << kMaxHashTableBits;
                         ^
                         ;
8 warnings and 9 errors generated.
make: *** [snappy-c.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/snappy-0.2.0 for inspection.
Results logged to /Users/alexanderlang/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/extensions/arm64-darwin-21/2.6.0/snappy-0.2.0/gem_make.out
```

**Comment by langalex** [comment]
well ok, after a bit more trial and error, this worked: `gem install snappy -- --with-cxxflags=-std=c++11`
